[versions]
spotless = "8.10.2"
shadow-jar = "9.6.1"
apacheCommonsLang = "3.20.0"
autoService = "1.1.1"
flogger = "0.9"
floggerBackend = "0.9"
gson = "2.14.0"
autoValue = "1.11.1"
autoValueAnnotations = "1.11.1"
guava = "33.7.1-jre"
univocityParsers = "2.9.1"
commonsCompress = "1.28.0"
mockito = "5.23.0"
junit = "4.13.2"
truth = "1.4.5"
truthExtension = "1.4.5"
javaxInject = "1"
httpClient5 = "5.6.4"
geometry = "2.0.0"
libphonenumber = "9.0.39"
classgraph = "4.8.195"
thymeleaf = "3.1.5.RELEASE"
locationtech = "1.20.0"
flexmark = "0.64.8"
commonsIO = "2.22.0"
commonsValidator = "1.11.0"
jcommander = "1.82"
javaPoet = "1.13.0"
apiClient = "2.9.1"
jetbrainsAnnotations = "26.1.0"
aspectjrt = "1.9.25.1"
aspectjrtweaver = "1.9.25.1"
findbugs = "3.0.2"
jspecify = "1.0.1"
jacksonDatabind = "2.22.2"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
shadow-jar = { id = "com.gradleup.shadow", version.ref = "shadow-jar" }

[libraries]
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apacheCommonsLang" }
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
flogger = { module = "com.google.flogger:flogger", version.ref = "flogger" }
flogger-system-backend = { module = "com.google.flogger:flogger-system-backend", version.ref = "floggerBackend" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
auto-value = { module = "com.google.auto.value:auto-value", version.ref = "autoValue" }
auto-value-annotations = { module = "com.google.auto.value:auto-value-annotations", version.ref = "autoValueAnnotations" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
univocity-parsers = { module = "com.univocity:univocity-parsers", version.ref = "univocityParsers" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
junit = { module = "junit:junit", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
truth-extension = { module = "com.google.truth.extensions:truth-java8-extension", version.ref = "truthExtension" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
httpclient5 = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "httpClient5" }
geometry = { module = "com.google.geometry:s2-geometry", version.ref = "geometry" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
location-tech = { module = "org.locationtech.jts:jts-core", version.ref = "locationtech" }
thymeleaf = { module = "org.thymeleaf:thymeleaf", version.ref = "thymeleaf" }
flexmark = { module = "com.vladsch.flexmark:flexmark-all", version.ref = "flexmark" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIO" }
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commonsValidator" }
jcommander = { module = "com.beust:jcommander", version.ref = "jcommander" }
java-poet = { module = "com.squareup:javapoet", version.ref = "javaPoet" }
api-client = { module = "com.google.api-client:google-api-client", version.ref = "apiClient" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
aspectjrt = { module = "org.aspectj:aspectjrt", version.ref = "aspectjrt" }
aspectjrt-weaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectjrtweaver" }
findbugs = { module = "com.google.code.findbugs:jsr305", version.ref = "findbugs" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonDatabind" }
slf4j-jul = { module = "org.slf4j:slf4j-jdk14", version = "2.0.19" }
